subdir = src/backend/optimizer/heuristic
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	counter.o \
	graph_utils.o \
	goo.o \
	heuristic_manager.o

include $(top_srcdir)/src/backend/common.mk